In [1]:
import sys 
import numpy as np

# numpy arrays


In [4]:
array1 = np.array([1,2,3,4,5])

In [5]:
array2 = np.array([6,7,8,9,10])

In [8]:
array1[0]

1

In [9]:
array2[0]

6

In [10]:
array1[0:]

array([1, 2, 3, 4, 5])

In [11]:
array2[0:-1]

array([6, 7, 8, 9])

In [20]:
array1[::-1]

array([5, 4, 3, 2, 1])

In [21]:
array2[[0,2,4]]

array([ 6,  8, 10])

# Array Types


In [22]:
array1.dtype

dtype('int64')

In [24]:
array1

array([1, 2, 3, 4, 5])

In [27]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [28]:
array3 = np.array(['a','b','c'])

In [29]:
array3.dtype

dtype('<U1')

In [30]:
array4 = np.array([{'a':1},2])

In [32]:
array4.dtype

dtype('O')

# Array Dimensions and shapes

In [33]:
array1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [34]:
array1.shape

(2, 3)

In [35]:
array1.ndim

2

In [36]:
array1.size

6

In [37]:
array2 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [38]:
array2.shape

(2, 2, 3)

In [39]:
array2.ndim

3

In [40]:
array2.size

12

# Indexing and Slicing 

In [41]:
array1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [43]:
array1[1]

array([4, 5, 6])

In [45]:
array1[1][0]

4

In [46]:
array1[1,0]

4

In [47]:
array1[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
array1[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [49]:
array1[:2, :2]

array([[1, 2],
       [4, 5]])

In [50]:
array1[:2, 2:]

array([[3],
       [6]])

In [51]:
array1[1] = np.array([0,0,0])

In [52]:
array1

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [53]:
array1[1,1] = np.array([5])

In [54]:
array1

array([[1, 2, 3],
       [0, 5, 0],
       [7, 8, 9]])

In [55]:
array1[1]= 0

In [56]:
array1

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

# statistics

In [57]:
array1 =np.array([1,2,3,4,5])

In [58]:
array1.sum()

15

In [59]:
array1.mean()

3.0

In [60]:
array1.std()

1.4142135623730951

In [61]:
array1.var()

2.0

In [62]:
array2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [63]:
array2.sum()

45

In [64]:
array2.mean()

5.0

In [67]:
array2.std()

2.581988897471611

In [68]:
array2.var()

6.666666666666667

In [69]:
array2.sum(axis=0)

array([12, 15, 18])

In [70]:
array2.sum(axis=1)

array([ 6, 15, 24])

In [71]:
array2.mean(axis = 1)

array([2., 5., 8.])

# Broadcasting and Vectorized operations

In [73]:
array1 = np.arange(5)

In [74]:
array1

array([0, 1, 2, 3, 4])

In [76]:
array1 + 10

array([10, 11, 12, 13, 14])

In [77]:
array1 * 10


array([ 0, 10, 20, 30, 40])

In [78]:
array1

array([0, 1, 2, 3, 4])

In [79]:
array1 += 10

In [85]:
array1 = np.arange(5)

In [82]:
array2 = np.arange(5,10)

In [83]:
array2

array([5, 6, 7, 8, 9])

In [86]:
array1 + array2

array([ 5,  7,  9, 11, 13])

In [87]:
array1 * array2

array([ 0,  6, 14, 24, 36])

# Boolean arrays (masks)

In [88]:
array1 = np.arange(5)

In [89]:
array1

array([0, 1, 2, 3, 4])

In [96]:
array1[[0,-1]]

array([0, 4])

In [99]:
array1[[True,False,False,False,True]]

array([0, 4])

In [100]:
array1 >= 2

array([False, False,  True,  True,  True])

In [101]:
array1[array1 >= 2]

array([2, 3, 4])

In [102]:
array1.mean()

2.0

In [103]:
array1[array1 > array1.mean()]

array([3, 4])

In [110]:
array1[~(array1 > array1.mean())]

array([0, 1, 2])

In [113]:
(array1 == 0) | (array1 == 1)

array([ True,  True, False, False, False])

In [114]:
array2 = np.random.randint(50, size=(3,3))

In [115]:
array2

array([[ 6, 45, 45],
       [47,  6, 42],
       [30, 11, 33]])

In [117]:
array2[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([ 6, 45,  6, 30, 33])

In [118]:
array2 > 30

array([[False,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [119]:
array2[array2>30]

array([45, 45, 47, 42, 33])

# Linear Algebra

In [120]:
array1= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [122]:
array2= np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [126]:
array1.dot(array2)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [128]:
array1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [129]:
array1 @ array2

array([[20, 14],
       [56, 41],
       [92, 68]])

In [179]:
array2.T @ array1

array([[36, 48, 60],
       [24, 33, 42]])

# Some Useful Functions

In [131]:
np.random.random(size=2)

array([0.19184523, 0.16643326])

In [134]:
np.random.normal(size=2)

array([-0.45527159, -1.55091684])

In [137]:
np.random.rand(2, 4)

array([[0.75120554, 0.4692889 , 0.71598549, 0.2852112 ],
       [0.82274128, 0.64673749, 0.11903622, 0.0166778 ]])

In [138]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [142]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [143]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [145]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [148]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [149]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [156]:
np.linspace(0, 4, 5, True)

array([0., 1., 2., 3., 4.])

In [157]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [158]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [162]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [170]:
np.empty((2, 2))

array([[1., 2.],
       [3., 4.]])

In [171]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [172]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
np.eye(8, 4, k=-4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [192]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [195]:
np.random.random((3,3,3))

array([[[0.28684987, 0.29657539, 0.08576725],
        [0.2956824 , 0.37099949, 0.25346809],
        [0.28084743, 0.66801739, 0.11909612]],

       [[0.20039635, 0.2160706 , 0.12032181],
        [0.3196435 , 0.36408296, 0.29721017],
        [0.78490882, 0.5592996 , 0.53139199]],

       [[0.72510095, 0.90960099, 0.77572676],
        [0.34939929, 0.17858084, 0.51471684],
        [0.28034563, 0.24866823, 0.88669086]]])